[project]
name = "shining-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "slsSong", email = "slsongxl@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.64.0",
]

[project.scripts]
shining-chatbot = "shining_chatbot:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
